Disabled github actions due to allure error
Error: Could not find or load main class io.qameta.allure.CommandLine
Caused by: java.lang.ClassNotFoundException: io.qameta.allure.CommandLine